### ISSUE TITLE
replace renv URL

### ISSUE THREAD

**Issue by benmarwick** [XD1NG/FL-site-formation-study#1]
https://github.com/XD1NG/FL-site-formation-study/blob/2e64dcf5ae153c87cc1e288503057db37b44d01f/FL_code.R#L1C1-L2C1

This line contains an redirected and obfuscated URL which is hard to read and might not work for future users. 

I recommend you change it to `renv::init(repos = "https://packagemanager.posit.co/cran/2023-10-03")`

**Comment by XD1NG** [comment]
Thank you very much! It has been replaced now

**Comment by benmarwick** [comment]
Thanks for your quick response!
